dependencies:
  - name: prometheus-operator
    version: "9.3.*"
    repository: https://charts.helm.sh/stable
    import-values:
    - child: grafana
      parent: grafana
    - child: prometheus
      parent: prometheus
