apiVersion: v1
kind: Secret
metadata:
  name: synapse-connector-config
  namespace: {{ template "synapse-prometheus-operator.namespace" . }}
  labels:
{{ include "synapse-prometheus-operator.labels" . | indent 4 }}
stringData:
  config.yaml: |-
{{ toYaml .Values.synapse | indent 4 }}
